/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlhanghoa;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class HangHoa extends javax.swing.JFrame {

    /**
     * Creates new form HangHoa
     */
    public HangHoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_maHang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_tenHang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_donGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbx_loaiHang = new javax.swing.JComboBox<>();
        cbx_nsx = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbx_dvt = new javax.swing.JComboBox<>();
        tf_ngayNhapHang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_themMoi = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã hàng hóa:");

        tf_maHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên hàng:");

        tf_tenHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Loại hàng:");

        tf_donGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Đơn giá:");

        cbx_loaiHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbx_loaiHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Điện thoại", "Máy tính", "Tivi" }));

        cbx_nsx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbx_nsx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sharp", "Samsung", "Toshiba" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nhà sản xuất:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Đơn vị tính:");

        cbx_dvt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbx_dvt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cái", "Chiếc" }));

        tf_ngayNhapHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ngày nhập hàng:");

        btn_themMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_themMoi.setText("Thêm mới");
        btn_themMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themMoiActionPerformed(evt);
            }
        });

        btn_huy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_huy.setText("Hủy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbx_loaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbx_nsx, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbx_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn_huy)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tf_ngayNhapHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                                    .addComponent(tf_donGia, javax.swing.GroupLayout.Alignment.LEADING))))
                                        .addGap(0, 15, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_maHang, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_tenHang)))))
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btn_themMoi)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_maHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_tenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbx_loaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbx_nsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbx_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tf_ngayNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themMoi)
                    .addComponent(btn_huy))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themMoiActionPerformed
        String maHang = tf_maHang.getText();
        String tenHang = tf_tenHang.getText();
        String loaiHang = (String) cbx_loaiHang.getSelectedItem();
        String nsx = (String) cbx_nsx.getSelectedItem();
        String dvt = (String) cbx_dvt.getSelectedItem();
        String donGia = tf_donGia.getText();
        String ngayNhapHang = tf_ngayNhapHang.getText();
        
        if(!maHang.matches("H[a-zA-Z0-9]{5}")){
            System.err.println("Ma hang hoa phai bat dau bang H va co 6 ky tu.");
        } else if(tenHang.isBlank()){
            System.err.println("Ten hang hoa khong duoc de rong.");
        } else if(!donGia.matches("\\d+")){
            System.err.println("Don gia phai la so lon hon 0.");
        } else if (!isValidDate(ngayNhapHang)) {
            System.err.println("Ngay nhap hang phai theo dinh dang dd/mm/yyyy va tu ngay hien tai ve sau.");
        } else{
            System.out.println("Ma hang: " + maHang);
            System.out.println("Ten hang: " + tenHang);
            System.out.println("Loai hang: " + loaiHang);
            System.out.println("Nha san xuat: " + nsx);
            System.out.println("Don vi tinh: " + dvt);
            System.out.println("Don gia: " + donGia);
            System.out.println("Ngay nhap hang: " + ngayNhapHang);
            
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl = "jdbc:sqlserver://MSI:1433;trustServerCertificate=true;databaseName=HangHoa;user=sa;password=123456";
                Connection connection = DriverManager.getConnection(dbUrl);
                String sql = "INSERT INTO hang_hoa(ma_hang, ten_hang, loai_hang, nha_san_xuat, don_vi_tinh, don_gia, ngay_nhap_hang)"
                        + " VALUES(?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pt = connection.prepareStatement(sql);
                pt.setString(1, maHang);
                pt.setString(2, tenHang);
                pt.setString(3, loaiHang);
                pt.setString(4, nsx);
                pt.setString(5, dvt);
                pt.setString(6, donGia);
                pt.setString(7, ngayNhapHang);
                pt.executeUpdate();
                System.out.println("Them thanh cong!");
                connection.close();
            } catch (Exception ex) {
                System.err.println("Ma hang da ton tai. Them that bai.");
            }
        }
    }//GEN-LAST:event_btn_themMoiActionPerformed

    public boolean isValidDate(String input){
        try {
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date currentDay = new Date();
            String currentDayCheck = df.format(currentDay);
            Date date = df.parse(input);
            if(currentDayCheck.equals(df.format(date)) || date.after(currentDay)){
                return true;
            }
        } catch (ParseException ex) {
            return false;
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_themMoi;
    private javax.swing.JComboBox<String> cbx_dvt;
    private javax.swing.JComboBox<String> cbx_loaiHang;
    private javax.swing.JComboBox<String> cbx_nsx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_donGia;
    private javax.swing.JTextField tf_maHang;
    private javax.swing.JTextField tf_ngayNhapHang;
    private javax.swing.JTextField tf_tenHang;
    // End of variables declaration//GEN-END:variables
}
