/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ttdat.swing;

import java.awt.event.ActionEvent;

/**
 *
 * @author Admin
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        setUpAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lb_soHoaDon = new javax.swing.JLabel();
        tf_soHoaDon = new javax.swing.JTextField();
        lb_maKH = new javax.swing.JLabel();
        tf_maKH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_tenKH = new javax.swing.JTextField();
        lb_soCMND = new javax.swing.JLabel();
        tf_soCMND = new javax.swing.JTextField();
        lb_soPhong = new javax.swing.JLabel();
        cbbx_soPhong = new javax.swing.JComboBox<>();
        lb_soTien = new javax.swing.JLabel();
        tf_soTien = new javax.swing.JTextField();
        btn_dongY = new javax.swing.JButton();
        btn_huyBo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        title.setText("Bảng thanh toán");

        lb_soHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_soHoaDon.setText("Số hóa đơn");

        tf_soHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lb_maKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_maKH.setText("Mã khách hàng");

        tf_maKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tên khách hàng");

        tf_tenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lb_soCMND.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_soCMND.setText("Số CMND");

        tf_soCMND.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lb_soPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_soPhong.setText("Số phòng");

        cbbx_soPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbbx_soPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "201", "301" }));

        lb_soTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_soTien.setText("Số tiền thanh toán");

        tf_soTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_dongY.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_dongY.setText("Đồng ý");

        btn_huyBo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_huyBo.setText("Hủy bỏ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lb_soHoaDon)
                                .addComponent(lb_maKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lb_soPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_soCMND, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lb_soTien))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_soHoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(tf_maKH, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbbx_soPhong, javax.swing.GroupLayout.Alignment.LEADING, 0, 127, Short.MAX_VALUE)
                                .addComponent(tf_soTien, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_soCMND, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btn_dongY)
                        .addGap(18, 18, 18)
                        .addComponent(btn_huyBo)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_soHoaDon)
                    .addComponent(tf_soHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_maKH)
                    .addComponent(tf_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_soCMND)
                    .addComponent(tf_soCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_soPhong)
                    .addComponent(cbbx_soPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_soTien)
                    .addComponent(tf_soTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dongY)
                    .addComponent(btn_huyBo))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Bill bill = new Bill();
            bill.setTitle("Khach san Phuong Nam");
            bill.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dongY;
    private javax.swing.JButton btn_huyBo;
    private javax.swing.JComboBox<String> cbbx_soPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_maKH;
    private javax.swing.JLabel lb_soCMND;
    private javax.swing.JLabel lb_soHoaDon;
    private javax.swing.JLabel lb_soPhong;
    private javax.swing.JLabel lb_soTien;
    private javax.swing.JTextField tf_maKH;
    private javax.swing.JTextField tf_soCMND;
    private javax.swing.JTextField tf_soHoaDon;
    private javax.swing.JTextField tf_soTien;
    private javax.swing.JTextField tf_tenKH;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void setUpAction(){
        btn_dongY.addActionListener((ActionEvent e) -> {
            validateInfo();
        });
        btn_huyBo.addActionListener((ActionEvent e) -> {
            reset();
        });
    }
    
    
    
    private void validateInfo(){
        String soHoaDon = tf_soHoaDon.getText();
        String maKH = tf_maKH.getText();
        String tenKH = tf_tenKH.getText();
        String soCMND = tf_soCMND.getText();
        String soPhong = (String) cbbx_soPhong.getSelectedItem();
        String soTien = tf_soTien.getText();
        
        if(soHoaDon.matches("\\d{4}") && maKH.matches("PN-\\d{4}") && !tenKH.isBlank()
            && soCMND.matches("\\d{9}") && soTien.matches("\\d+")){
            System.out.println("Số hóa đơn: " + soHoaDon);
            System.out.println("Mã khách hàng: " + maKH);
            System.out.println("Tên khách hàng: " + tenKH);
            System.out.println("Số CMND: " + soCMND);
            System.out.println("Số phòng: " + soPhong);
            System.out.println("Số tiền thanh toán: " + soTien);
        } else{
            if(!soHoaDon.matches("\\d{4}")){
                System.err.println("Số hóa đơn phải gồm 4 chữ số.");
            }
            if(!maKH.matches("PN-\\d{4}")){
                System.err.println("Mã khách hàng phải có dạng PN-XXXX (X là chữ số).");
            }
            if(tenKH.isBlank()){
                System.err.println("Tên khách hàng không được để rỗng.");
            }
            if(!soCMND.matches("\\d{9}")){
                System.err.println("Số CMND phải gồm 9 chữ số.");
            }
            if(!soTien.matches("\\d+")){
                System.err.println("Số tiền nhập vào phải là số.");
            }
        }
    }
    
    private void reset(){
        tf_soHoaDon.setText("");
        tf_maKH.setText("");
        tf_tenKH.setText("");
        tf_soCMND.setText("");
        cbbx_soPhong.setSelectedIndex(0);
        tf_soTien.setText("");
    }
    
}
